import crypto from 'node:crypto'
import path from 'node:path'
import os from 'node:os'

/**
 * Generate a unique workspace ID from a workspace path
 *
 * The workspace ID is generated by:
 * 1. Normalizing the path (resolving to absolute path)
 * 2. Creating a SHA-256 hash of the normalized path
 * 3. Taking the first 16 characters of the hash
 *
 * This ensures that:
 * - Same workspace path always generates the same ID
 * - Different workspace paths generate different IDs
 * - IDs are short and human-readable (16 chars)
 *
 * @param workspacePath - Absolute or relative path to the workspace
 * @returns A unique workspace ID (16-character hex string)
 */
export function generateWorkspaceId(workspacePath: string): string {
  // Normalize the path to an absolute path
  const normalizedPath = path.resolve(workspacePath)

  // Replace Windows backslashes with forward slashes for consistency
  const canonicalPath = normalizedPath.replace(/\\/g, '/')

  // Create a hash of the canonical path
  const hash = crypto.createHash('sha256').update(canonicalPath).digest('hex')

  // Return the first 16 characters of the hash
  return hash.substring(0, 16)
}

/**
 * Get a human-readable workspace name from a workspace path
 *
 * This is useful for display purposes (e.g., in logs or UI).
 *
 * @param workspacePath - Absolute or relative path to the workspace
 * @returns A human-readable workspace name
 */
export function getWorkspaceName(workspacePath: string): string {
  const normalizedPath = path.resolve(workspacePath)
  return path.basename(normalizedPath)
}

/**
 * Normalize a workspace path to a canonical form
 *
 * This ensures consistent path handling across different platforms:
 * - Converts to absolute path
 * - Replaces backslashes with forward slashes (Windows compatibility)
 * - Resolves symbolic links
 * - Expands ~ to home directory
 *
 * @param workspacePath - Absolute or relative path to the workspace
 * @returns Canonical workspace path
 */
export function normalizeWorkspacePath(workspacePath: string): string {
  // Expand ~ to home directory
  let expandedPath = workspacePath
  if (workspacePath.startsWith('~')) {
    expandedPath = path.join(os.homedir(), workspacePath.slice(1))
  }

  // Resolve to absolute path
  const absolutePath = path.resolve(expandedPath)

  // Replace backslashes with forward slashes for consistency
  return absolutePath.replace(/\\/g, '/')
}

/**
 * Get the base temporary directory for local-knowledge-rag-mcp
 *
 * Path format: /tmp/local-knowledge-rag-mcp/
 *
 * @returns Absolute path to the base temporary directory
 */
export function getBaseTempDir(): string {
  return path.join(os.tmpdir(), 'local-knowledge-rag-mcp')
}

/**
 * Get the system temporary directory path for a workspace
 *
 * Returns a workspace-specific temporary directory path for storing
 * transient files like progress logs.
 *
 * Path format: /tmp/local-knowledge-rag-mcp/{workspaceId}/
 *
 * @param workspaceId - Unique workspace identifier (16-character hex string)
 * @returns Absolute path to the workspace temporary directory
 */
export function getWorkspaceTempDir(workspaceId: string): string {
  return path.join(getBaseTempDir(), workspaceId)
}
